#Box Graphics
#Do not input indentations in order to avoid errors if copied and pasted
	import turtle
	t = turtle.Pen()
	t.forward(50)
	t.left(45)
	t.up()
	t.forward(50)
	t.down()
	t.left(45)
	t.forward(50)
	t.left(45)
	t.up()
	t.forward(50)
	t.down()
	t.left(45)
	t.forward(50)
	t.left(45)
	t.up()
	t.forward(50)
	t.down()
	t.left(45)
	t.forward(50)
	t.left(45)
	t.up()
	t.forward(50)
	t.down()
	t.left(45)
